[global.databases.db]
url = "postgres://postgres@localhost/as207960_esign"

[debug]
secret_key = "5wgweFk40X4dKh7Ds7G8cn/x3TTykhsYmH3B+v3XQ2o="
files_key = "hcIyyVf74bYQK6bxdDmvgxsxI593+MjDCSXfXHhdZMQ="
celery = { amqp_url = "amqp://localhost:5672/as207960_esign" }
external_uri = "https://as207960-esign.eu.ngrok.io"

[debug.oidc]
issuer_url = "https://sso.as207960.net/auth/realms/dev"
client_id = "esign"
client_secret = "558ef97e-361a-42d7-8ddb-5881eff610df"

[debug.smtp]
server = "mx.postal.as207960.net"
port = 25
use_tls = true

[debug.smtp.auth]
username = "as207960/main"
password = "K47LyJQ8QYWPlPnwighr5F65"

[debug.signing]
cert = "priv/cert.pem"
cert_chain = []
hsm_pin = ""
pkcs11_key_id = ""